name: 'AliyunCli Action'
description: 'Action for aliyun cli.'
inputs:
  secrets:
    description: 'The secrets to use.'
    required: true
  version:
    description: 'The version number of aliyun-cli to download'
    required: false
    default: '3.0.121'
outputs: {}


runs:
  using: "composite"
  env: 
    ALIBABACLOUD_ACCESS_KEY_ID: ${{ inputs.secrets.ALIBABACLOUD_ACCESS_KEY_ID }}
    ALIBABACLOUD_ACCESS_KEY_SECRET: ${{ inputs.secrets.ALIBABACLOUD_ACCESS_KEY_SECRET }}
    ALIBABACLOUD_REGION_ID: ${{ inputs.secrets.ALIBABACLOUD_REGION_ID }}
  
  steps:
    - name: Install aliyun cli
      shell: bash
      run: |
        curl -sL https://github.com/aliyun/aliyun-cli/releases/download/v${{ inputs.version }}/aliyun-cli-linux-${{ inputs.version }}-amd64.tgz | tar -xzf - -C /usr/local/bin --strip-components=1 aliyun
        aliyun --version
        printenv
    