name: 'AliyunCli Action'
description: 'Action for aliyun cli.'
inputs:
  aliyun_secrets:
    description: 'The aliyun secrets(ACCESS_KEY_ID, ACCESS_KEY_SECRET, REGION_ID)'
    required: true
  version:
    description: 'The version number of aliyun-cli to download'
    required: false
    default: '3.0.121'
outputs: {}


runs:
  using: "composite"
  steps:
    - name: Install aliyun cli
      shell: bash
      run: |
        # set envs 
        export $(awk 'NF {sub(/\r/, ""); print "export " $0}' ${{ inputs.aliyun_secrets }})
        
        # install aliyun-cli
        curl -sL https://github.com/aliyun/aliyun-cli/releases/download/v${{ inputs.version }}/aliyun-cli-linux-${{ inputs.version }}-amd64.tgz | tar -xzf - -C /usr/local/bin --strip-components=1 aliyun
        aliyun --version
        printenv
    