name: 'AliyunCli Action'
description: 'Action for aliyun cli.'
inputs:
  version:
    description: 'The version number of aliyun-cli to download'
    required: false
    default: '3.0.121'
outputs: {}
runs:
  using: "composite"
  steps:
    - name: Install aliyun cli
      shell: bash
      run: |
        curl -sL https://github.com/aliyun/aliyun-cli/releases/download/v${{ inputs.version }}/aliyun-cli-linux-${{ inputs.version }}-amd64.tgz | tar -xzf - -C /usr/local/bin --strip-components=1 aliyun
        aliyun --version