name: 'AliyunCli Action'
description: 'Action for aliyun cli.'
inputs:
  version:
    description: 'The version number of aliyun-cli to download'
    required: false
    default: '3.0.121'
outputs: {}

env: 
  ALIYUN_ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY_ID }}
  ALIYUN_ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}
  ALIBABACLOUD_REGION_ID: ${{ secrets.ALIBABACLOUD_REGION_ID }}

runs:
  using: "composite"
  steps:
    - name: Install aliyun cli
      shell: bash
      run: |
        curl -sL https://github.com/aliyun/aliyun-cli/releases/download/v${{ inputs.version }}/aliyun-cli-linux-${{ inputs.version }}-amd64.tgz | tar -xzf - -C /usr/local/bin --strip-components=1 aliyun
        aliyun --version
    
    - name: Set env from secrets
      shell: bash
      run: |
        aliyun configure set --mode AK --access-key-id $ALIYUN_ACCESS_KEY_ID --access-key-secret $ALIYUN_ACCESS_KEY_SECRET --region-id $ALIBABACLOUD_REGION_ID
        aliyun configure list