name: aliyun-cli test workflow
on: [push]
jobs:
  hello:
    name: test aliyun-cli
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use aliyun-cli v3.0.152
        uses: afeiship/action-aliyun-cli@master
        with:
          version: '3.0.152'

      - name: Debug
        run: |
          printenv
          aliyun --version